//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlzhCareHub.StringResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlzhCareHub.StringResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a1para.
        /// </summary>
        public static string a1para {
            get {
                return ResourceManager.GetString("a1para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a2head.
        /// </summary>
        public static string a2head {
            get {
                return ResourceManager.GetString("a2head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a2para.
        /// </summary>
        public static string a2para {
            get {
                return ResourceManager.GetString("a2para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a3btn.
        /// </summary>
        public static string a3btn {
            get {
                return ResourceManager.GetString("a3btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a3head.
        /// </summary>
        public static string a3head {
            get {
                return ResourceManager.GetString("a3head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a3para.
        /// </summary>
        public static string a3para {
            get {
                return ResourceManager.GetString("a3para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutUs .
        /// </summary>
        public static string AboutUs_ {
            get {
                return ResourceManager.GetString("AboutUs ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutUsHeroHead.
        /// </summary>
        public static string AboutUsHeroHead {
            get {
                return ResourceManager.GetString("AboutUsHeroHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutUsHeroPara.
        /// </summary>
        public static string AboutUsHeroPara {
            get {
                return ResourceManager.GetString("AboutUsHeroPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutUsVideoHead.
        /// </summary>
        public static string AboutUsVideoHead {
            get {
                return ResourceManager.GetString("AboutUsVideoHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adownload.
        /// </summary>
        public static string adownload {
            get {
                return ResourceManager.GetString("adownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AHead.
        /// </summary>
        public static string AHead {
            get {
                return ResourceManager.GetString("AHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlreadyAccount.
        /// </summary>
        public static string AlreadyAccount {
            get {
                return ResourceManager.GetString("AlreadyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlzhCare.
        /// </summary>
        public static string AlzhCare {
            get {
                return ResourceManager.GetString("AlzhCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppsAndGames.
        /// </summary>
        public static string AppsAndGames {
            get {
                return ResourceManager.GetString("AppsAndGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arhead1.
        /// </summary>
        public static string arhead1 {
            get {
                return ResourceManager.GetString("arhead1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactSupport.
        /// </summary>
        public static string ContactSupport {
            get {
                return ResourceManager.GetString("ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string Create_account {
            get {
                return ResourceManager.GetString("Create account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateAccount.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dap.
        /// </summary>
        public static string dap {
            get {
                return ResourceManager.GetString("dap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dappara.
        /// </summary>
        public static string dappara {
            get {
                return ResourceManager.GetString("dappara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DonateHead.
        /// </summary>
        public static string DonateHead {
            get {
                return ResourceManager.GetString("DonateHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DonatePara.
        /// </summary>
        public static string DonatePara {
            get {
                return ResourceManager.GetString("DonatePara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationalResources.
        /// </summary>
        public static string EducationalResources {
            get {
                return ResourceManager.GetString("EducationalResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faq.
        /// </summary>
        public static string faq {
            get {
                return ResourceManager.GetString("faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedback.
        /// </summary>
        public static string feedback {
            get {
                return ResourceManager.GetString("feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedpara.
        /// </summary>
        public static string feedpara {
            get {
                return ResourceManager.GetString("feedpara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindDoctor.
        /// </summary>
        public static string FindDoctor {
            get {
                return ResourceManager.GetString("FindDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fp.
        /// </summary>
        public static string fp {
            get {
                return ResourceManager.GetString("fp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetHelp.
        /// </summary>
        public static string GetHelp {
            get {
                return ResourceManager.GetString("GetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gp.
        /// </summary>
        public static string gp {
            get {
                return ResourceManager.GetString("gp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpCenter.
        /// </summary>
        public static string HelpCenter {
            get {
                return ResourceManager.GetString("HelpCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeroPara.
        /// </summary>
        public static string HeroPara {
            get {
                return ResourceManager.GetString("HeroPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeroText.
        /// </summary>
        public static string HeroText {
            get {
                return ResourceManager.GetString("HeroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islamabad.
        /// </summary>
        public static string Islamabad {
            get {
                return ResourceManager.GetString("Islamabad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JoinHead.
        /// </summary>
        public static string JoinHead {
            get {
                return ResourceManager.GetString("JoinHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JoinPara.
        /// </summary>
        public static string JoinPara {
            get {
                return ResourceManager.GetString("JoinPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karachi.
        /// </summary>
        public static string Karachi {
            get {
                return ResourceManager.GetString("Karachi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lahore.
        /// </summary>
        public static string Lahore {
            get {
                return ResourceManager.GetString("Lahore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LM.
        /// </summary>
        public static string LM {
            get {
                return ResourceManager.GetString("LM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login .
        /// </summary>
        public static string Login_ {
            get {
                return ResourceManager.GetString("Login ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginHead.
        /// </summary>
        public static string LoginHead {
            get {
                return ResourceManager.GetString("LoginHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginHere.
        /// </summary>
        public static string LoginHere {
            get {
                return ResourceManager.GetString("LoginHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginPara.
        /// </summary>
        public static string LoginPara {
            get {
                return ResourceManager.GetString("LoginPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mulla Wala.
        /// </summary>
        public static string Mulla_Wala {
            get {
                return ResourceManager.GetString("Mulla Wala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterText.
        /// </summary>
        public static string RegisterText {
            get {
                return ResourceManager.GetString("RegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remainder.
        /// </summary>
        public static string Remainder {
            get {
                return ResourceManager.GetString("Remainder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemainderPara.
        /// </summary>
        public static string RemainderPara {
            get {
                return ResourceManager.GetString("RemainderPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights.
        /// </summary>
        public static string Rigths {
            get {
                return ResourceManager.GetString("Rigths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServicesPara.
        /// </summary>
        public static string ServicesPara {
            get {
                return ResourceManager.GetString("ServicesPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonials.
        /// </summary>
        public static string Testimonials {
            get {
                return ResourceManager.GetString("Testimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tp.
        /// </summary>
        public static string tp {
            get {
                return ResourceManager.GetString("tp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrainingResources.
        /// </summary>
        public static string TrainingResources {
            get {
                return ResourceManager.GetString("TrainingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer.
        /// </summary>
        public static string Volunteer {
            get {
                return ResourceManager.GetString("Volunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlzhCare Hub A platform where there is a release of burden from Caregivers to their Old People for take care..
        /// </summary>
        public static string WebSiteFooterText {
            get {
                return ResourceManager.GetString("WebSiteFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works.
        /// </summary>
        public static string Works {
            get {
                return ResourceManager.GetString("Works", resourceCulture);
            }
        }
    }
}
