//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlzhCareHub.StringResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlzhCareHub.StringResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a1para.
        /// </summary>
        public static string a1para {
            get {
                return ResourceManager.GetString("a1para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a2head.
        /// </summary>
        public static string a2head {
            get {
                return ResourceManager.GetString("a2head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a2para.
        /// </summary>
        public static string a2para {
            get {
                return ResourceManager.GetString("a2para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a3btn.
        /// </summary>
        public static string a3btn {
            get {
                return ResourceManager.GetString("a3btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a3head.
        /// </summary>
        public static string a3head {
            get {
                return ResourceManager.GetString("a3head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a3para.
        /// </summary>
        public static string a3para {
            get {
                return ResourceManager.GetString("a3para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutUs .
        /// </summary>
        public static string AboutUs_ {
            get {
                return ResourceManager.GetString("AboutUs ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutUsHeroHead.
        /// </summary>
        public static string AboutUsHeroHead {
            get {
                return ResourceManager.GetString("AboutUsHeroHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutUsHeroPara.
        /// </summary>
        public static string AboutUsHeroPara {
            get {
                return ResourceManager.GetString("AboutUsHeroPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutUsVideoHead.
        /// </summary>
        public static string AboutUsVideoHead {
            get {
                return ResourceManager.GetString("AboutUsVideoHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adownload.
        /// </summary>
        public static string adownload {
            get {
                return ResourceManager.GetString("adownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AHead.
        /// </summary>
        public static string AHead {
            get {
                return ResourceManager.GetString("AHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlreadyAccount.
        /// </summary>
        public static string AlreadyAccount {
            get {
                return ResourceManager.GetString("AlreadyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlzhCare.
        /// </summary>
        public static string AlzhCare {
            get {
                return ResourceManager.GetString("AlzhCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlzhStageHead.
        /// </summary>
        public static string AlzhStageHead {
            get {
                return ResourceManager.GetString("AlzhStageHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ans6point1.
        /// </summary>
        public static string ans6point1 {
            get {
                return ResourceManager.GetString("ans6point1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppsAndGames.
        /// </summary>
        public static string AppsAndGames {
            get {
                return ResourceManager.GetString("AppsAndGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arhead1.
        /// </summary>
        public static string arhead1 {
            get {
                return ResourceManager.GetString("arhead1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelBtn.
        /// </summary>
        public static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckoutBtn.
        /// </summary>
        public static string CheckoutBtn {
            get {
                return ResourceManager.GetString("CheckoutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checkresponse.
        /// </summary>
        public static string checkresponse {
            get {
                return ResourceManager.GetString("checkresponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionWatsapp.
        /// </summary>
        public static string ConnectionWatsapp {
            get {
                return ResourceManager.GetString("ConnectionWatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactAddress.
        /// </summary>
        public static string ContactAdddress {
            get {
                return ResourceManager.GetString("ContactAdddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactInfo.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactPara.
        /// </summary>
        public static string ContactPara {
            get {
                return ResourceManager.GetString("ContactPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactSupport.
        /// </summary>
        public static string ContactSupport {
            get {
                return ResourceManager.GetString("ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactUs.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CostofEducation.
        /// </summary>
        public static string CostofEducation {
            get {
                return ResourceManager.GetString("CostofEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string Create_account {
            get {
                return ResourceManager.GetString("Create account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateAccount.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dap.
        /// </summary>
        public static string dap {
            get {
                return ResourceManager.GetString("dap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dappara.
        /// </summary>
        public static string dappara {
            get {
                return ResourceManager.GetString("dappara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateLabel.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc1Name.
        /// </summary>
        public static string Doc1Name {
            get {
                return ResourceManager.GetString("Doc1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoctorHead.
        /// </summary>
        public static string DoctorHead {
            get {
                return ResourceManager.GetString("DoctorHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoctorPara.
        /// </summary>
        public static string DoctorPara {
            get {
                return ResourceManager.GetString("DoctorPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoctorSecondHead.
        /// </summary>
        public static string DoctorSecondHead {
            get {
                return ResourceManager.GetString("DoctorSecondHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DonateHead.
        /// </summary>
        public static string DonateHead {
            get {
                return ResourceManager.GetString("DonateHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DonatePara.
        /// </summary>
        public static string DonatePara {
            get {
                return ResourceManager.GetString("DonatePara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donationAmount.
        /// </summary>
        public static string donationAmount {
            get {
                return ResourceManager.GetString("donationAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DonationFrequency.
        /// </summary>
        public static string DonationFrequency {
            get {
                return ResourceManager.GetString("DonationFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donationtype.
        /// </summary>
        public static string donationtype {
            get {
                return ResourceManager.GetString("donationtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAD.
        /// </summary>
        public static string EAD {
            get {
                return ResourceManager.GetString("EAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarlyHead.
        /// </summary>
        public static string EarlyHead {
            get {
                return ResourceManager.GetString("EarlyHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarlyStageGoal.
        /// </summary>
        public static string EarlyStageGoal {
            get {
                return ResourceManager.GetString("EarlyStageGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarlyStageHead.
        /// </summary>
        public static string EarlyStageHead {
            get {
                return ResourceManager.GetString("EarlyStageHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationalResources.
        /// </summary>
        public static string EducationalResources {
            get {
                return ResourceManager.GetString("EducationalResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailInput.
        /// </summary>
        public static string EmailInput {
            get {
                return ResourceManager.GetString("EmailInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailLabel.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails.
        /// </summary>
        public static string Emails {
            get {
                return ResourceManager.GetString("Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnglishLink.
        /// </summary>
        public static string EnglishLink {
            get {
                return ResourceManager.GetString("EnglishLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnterAmount.
        /// </summary>
        public static string EnterAmount {
            get {
                return ResourceManager.GetString("EnterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er1.
        /// </summary>
        public static string Er1 {
            get {
                return ResourceManager.GetString("Er1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er2.
        /// </summary>
        public static string Er2 {
            get {
                return ResourceManager.GetString("Er2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er3.
        /// </summary>
        public static string Er3 {
            get {
                return ResourceManager.GetString("Er3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERSE1.
        /// </summary>
        public static string ERSE1 {
            get {
                return ResourceManager.GetString("ERSE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERSEng1.
        /// </summary>
        public static string ERSEng1 {
            get {
                return ResourceManager.GetString("ERSEng1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es1.
        /// </summary>
        public static string Es1 {
            get {
                return ResourceManager.GetString("Es1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es2.
        /// </summary>
        public static string Es2 {
            get {
                return ResourceManager.GetString("Es2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es3.
        /// </summary>
        public static string Es3 {
            get {
                return ResourceManager.GetString("Es3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es4.
        /// </summary>
        public static string Es4 {
            get {
                return ResourceManager.GetString("Es4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faq.
        /// </summary>
        public static string faq {
            get {
                return ResourceManager.GetString("faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faqans1.
        /// </summary>
        public static string faqans1 {
            get {
                return ResourceManager.GetString("faqans1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faqans2point1.
        /// </summary>
        public static string faqans2point1 {
            get {
                return ResourceManager.GetString("faqans2point1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faqans2point2.
        /// </summary>
        public static string faqans2point2 {
            get {
                return ResourceManager.GetString("faqans2point2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faqans2point3.
        /// </summary>
        public static string faqans2point3 {
            get {
                return ResourceManager.GetString("faqans2point3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faqans2point4.
        /// </summary>
        public static string faqans2point4 {
            get {
                return ResourceManager.GetString("faqans2point4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faqans4.
        /// </summary>
        public static string faqans4 {
            get {
                return ResourceManager.GetString("faqans4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faqans5.
        /// </summary>
        public static string faqans5 {
            get {
                return ResourceManager.GetString("faqans5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faqans6point2.
        /// </summary>
        public static string faqans6point2 {
            get {
                return ResourceManager.GetString("faqans6point2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faqans6point3.
        /// </summary>
        public static string faqans6point3 {
            get {
                return ResourceManager.GetString("faqans6point3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faqhead.
        /// </summary>
        public static string faqhead {
            get {
                return ResourceManager.GetString("faqhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faqques5.
        /// </summary>
        public static string faqques5 {
            get {
                return ResourceManager.GetString("faqques5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faqques6.
        /// </summary>
        public static string faqques6 {
            get {
                return ResourceManager.GetString("faqques6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fb.
        /// </summary>
        public static string fb {
            get {
                return ResourceManager.GetString("fb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedback.
        /// </summary>
        public static string feedback {
            get {
                return ResourceManager.GetString("feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedpara.
        /// </summary>
        public static string feedpara {
            get {
                return ResourceManager.GetString("feedpara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindDoctor.
        /// </summary>
        public static string FindDoctor {
            get {
                return ResourceManager.GetString("FindDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fp.
        /// </summary>
        public static string fp {
            get {
                return ResourceManager.GetString("fp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetHelp.
        /// </summary>
        public static string GetHelp {
            get {
                return ResourceManager.GetString("GetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetVolunteerAssisstance.
        /// </summary>
        public static string GetVolunteerAssisstance {
            get {
                return ResourceManager.GetString("GetVolunteerAssisstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gp.
        /// </summary>
        public static string gp {
            get {
                return ResourceManager.GetString("gp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpCenter.
        /// </summary>
        public static string HelpCenter {
            get {
                return ResourceManager.GetString("HelpCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeroPara.
        /// </summary>
        public static string HeroPara {
            get {
                return ResourceManager.GetString("HeroPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeroText.
        /// </summary>
        public static string HeroText {
            get {
                return ResourceManager.GetString("HeroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to highGoal.
        /// </summary>
        public static string highGoal {
            get {
                return ResourceManager.GetString("highGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to highs1.
        /// </summary>
        public static string highs1 {
            get {
                return ResourceManager.GetString("highs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to highs2.
        /// </summary>
        public static string highs2 {
            get {
                return ResourceManager.GetString("highs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to highs3.
        /// </summary>
        public static string highs3 {
            get {
                return ResourceManager.GetString("highs3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to highstagehead.
        /// </summary>
        public static string highstagehead {
            get {
                return ResourceManager.GetString("highstagehead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to highsuggestedSteps.
        /// </summary>
        public static string highsuggestedSteps {
            get {
                return ResourceManager.GetString("highsuggestedSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs2.
        /// </summary>
        public static string hrs1 {
            get {
                return ResourceManager.GetString("hrs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs2.
        /// </summary>
        public static string hrs2 {
            get {
                return ResourceManager.GetString("hrs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs3.
        /// </summary>
        public static string hrs3 {
            get {
                return ResourceManager.GetString("hrs3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Islamabad.
        /// </summary>
        public static string Islamabad {
            get {
                return ResourceManager.GetString("Islamabad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JoinHead.
        /// </summary>
        public static string JoinHead {
            get {
                return ResourceManager.GetString("JoinHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JoinPara.
        /// </summary>
        public static string JoinPara {
            get {
                return ResourceManager.GetString("JoinPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JoinUs.
        /// </summary>
        public static string JoinUs {
            get {
                return ResourceManager.GetString("JoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karachi.
        /// </summary>
        public static string Karachi {
            get {
                return ResourceManager.GetString("Karachi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lahore.
        /// </summary>
        public static string Lahore {
            get {
                return ResourceManager.GetString("Lahore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LM.
        /// </summary>
        public static string LM {
            get {
                return ResourceManager.GetString("LM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login .
        /// </summary>
        public static string Login_ {
            get {
                return ResourceManager.GetString("Login ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginHead.
        /// </summary>
        public static string LoginHead {
            get {
                return ResourceManager.GetString("LoginHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginHere.
        /// </summary>
        public static string LoginHere {
            get {
                return ResourceManager.GetString("LoginHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginPara.
        /// </summary>
        public static string LoginPara {
            get {
                return ResourceManager.GetString("LoginPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModerateGoal.
        /// </summary>
        public static string ModerateGoal {
            get {
                return ResourceManager.GetString("ModerateGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModerateHead.
        /// </summary>
        public static string ModerateHead {
            get {
                return ResourceManager.GetString("ModerateHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModerateStageHead.
        /// </summary>
        public static string ModerateStageHead {
            get {
                return ResourceManager.GetString("ModerateStageHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mr1.
        /// </summary>
        public static string mr1 {
            get {
                return ResourceManager.GetString("mr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mr2.
        /// </summary>
        public static string mr2 {
            get {
                return ResourceManager.GetString("mr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mr3.
        /// </summary>
        public static string mr3 {
            get {
                return ResourceManager.GetString("mr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms1.
        /// </summary>
        public static string ms1 {
            get {
                return ResourceManager.GetString("ms1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms2.
        /// </summary>
        public static string ms2 {
            get {
                return ResourceManager.GetString("ms2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms3.
        /// </summary>
        public static string ms3 {
            get {
                return ResourceManager.GetString("ms3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msg.
        /// </summary>
        public static string msg {
            get {
                return ResourceManager.GetString("msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mulla Wala.
        /// </summary>
        public static string Mulla_Wala {
            get {
                return ResourceManager.GetString("Mulla Wala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o1.
        /// </summary>
        public static string o1 {
            get {
                return ResourceManager.GetString("o1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o2.
        /// </summary>
        public static string o2 {
            get {
                return ResourceManager.GetString("o2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o3.
        /// </summary>
        public static string o3 {
            get {
                return ResourceManager.GetString("o3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneTime.
        /// </summary>
        public static string OneTime {
            get {
                return ResourceManager.GetString("OneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OurTeam.
        /// </summary>
        public static string OurTeam {
            get {
                return ResourceManager.GetString("OurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P1.
        /// </summary>
        public static string P1 {
            get {
                return ResourceManager.GetString("P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P2.
        /// </summary>
        public static string P2 {
            get {
                return ResourceManager.GetString("P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P3.
        /// </summary>
        public static string P3 {
            get {
                return ResourceManager.GetString("P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PatientCare.
        /// </summary>
        public static string PateintCare {
            get {
                return ResourceManager.GetString("PateintCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PExp.
        /// </summary>
        public static string PExp {
            get {
                return ResourceManager.GetString("PExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to predictHighStage.
        /// </summary>
        public static string predictHighStage {
            get {
                return ResourceManager.GetString("predictHighStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q1.
        /// </summary>
        public static string q1 {
            get {
                return ResourceManager.GetString("q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q10.
        /// </summary>
        public static string q10 {
            get {
                return ResourceManager.GetString("q10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q2.
        /// </summary>
        public static string q2 {
            get {
                return ResourceManager.GetString("q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q3.
        /// </summary>
        public static string q3 {
            get {
                return ResourceManager.GetString("q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q4.
        /// </summary>
        public static string q4 {
            get {
                return ResourceManager.GetString("q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q5.
        /// </summary>
        public static string q5 {
            get {
                return ResourceManager.GetString("q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q6.
        /// </summary>
        public static string q6 {
            get {
                return ResourceManager.GetString("q6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q7.
        /// </summary>
        public static string q7 {
            get {
                return ResourceManager.GetString("q7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q8.
        /// </summary>
        public static string q8 {
            get {
                return ResourceManager.GetString("q8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q9.
        /// </summary>
        public static string q9 {
            get {
                return ResourceManager.GetString("q9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ques1.
        /// </summary>
        public static string ques1 {
            get {
                return ResourceManager.GetString("ques1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ques2.
        /// </summary>
        public static string ques2 {
            get {
                return ResourceManager.GetString("ques2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ques3.
        /// </summary>
        public static string ques3 {
            get {
                return ResourceManager.GetString("ques3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ques6head.
        /// </summary>
        public static string ques6head {
            get {
                return ResourceManager.GetString("ques6head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to queshead2.
        /// </summary>
        public static string queshead2 {
            get {
                return ResourceManager.GetString("queshead2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to questioneryBtn.
        /// </summary>
        public static string questioneryBtn {
            get {
                return ResourceManager.GetString("questioneryBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterText.
        /// </summary>
        public static string RegisterText {
            get {
                return ResourceManager.GetString("RegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remainder.
        /// </summary>
        public static string Remainder {
            get {
                return ResourceManager.GetString("Remainder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemainderPara.
        /// </summary>
        public static string RemainderPara {
            get {
                return ResourceManager.GetString("RemainderPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resouces.
        /// </summary>
        public static string Resouces {
            get {
                return ResourceManager.GetString("Resouces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights.
        /// </summary>
        public static string Rigths {
            get {
                return ResourceManager.GetString("Rigths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaySomething.
        /// </summary>
        public static string SaySomething {
            get {
                return ResourceManager.GetString("SaySomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServicesPara.
        /// </summary>
        public static string ServicesPara {
            get {
                return ResourceManager.GetString("ServicesPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBtn.
        /// </summary>
        public static string SetBtn {
            get {
                return ResourceManager.GetString("SetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sfb.
        /// </summary>
        public static string sfb {
            get {
                return ResourceManager.GetString("sfb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SndMsg.
        /// </summary>
        public static string SndMsg {
            get {
                return ResourceManager.GetString("SndMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitbtn.
        /// </summary>
        public static string Submitbtn {
            get {
                return ResourceManager.GetString("Submitbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmitFeedBack.
        /// </summary>
        public static string SubmitFeedBack {
            get {
                return ResourceManager.GetString("SubmitFeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupportOurWebsite.
        /// </summary>
        public static string SupportOurWebsite {
            get {
                return ResourceManager.GetString("SupportOurWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskDescription.
        /// </summary>
        public static string TaskDescription {
            get {
                return ResourceManager.GetString("TaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskHead.
        /// </summary>
        public static string TaskHead {
            get {
                return ResourceManager.GetString("TaskHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskHere.
        /// </summary>
        public static string TaskHere {
            get {
                return ResourceManager.GetString("TaskHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskLink.
        /// </summary>
        public static string TaskLink {
            get {
                return ResourceManager.GetString("TaskLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonials.
        /// </summary>
        public static string Testimonials {
            get {
                return ResourceManager.GetString("Testimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeLabel.
        /// </summary>
        public static string TimeLabel {
            get {
                return ResourceManager.GetString("TimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TitleLabel.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tp.
        /// </summary>
        public static string tp {
            get {
                return ResourceManager.GetString("tp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrainingResources.
        /// </summary>
        public static string TrainingResources {
            get {
                return ResourceManager.GetString("TrainingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeMsg.
        /// </summary>
        public static string TypeMsg {
            get {
                return ResourceManager.GetString("TypeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urdulink.
        /// </summary>
        public static string urdulink {
            get {
                return ResourceManager.GetString("urdulink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VDays.
        /// </summary>
        public static string VDays {
            get {
                return ResourceManager.GetString("VDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlabel2.
        /// </summary>
        public static string Vlabel2 {
            get {
                return ResourceManager.GetString("Vlabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlabel3.
        /// </summary>
        public static string Vlaebl3 {
            get {
                return ResourceManager.GetString("Vlaebl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VNo.
        /// </summary>
        public static string VNO {
            get {
                return ResourceManager.GetString("VNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer.
        /// </summary>
        public static string Volunteer {
            get {
                return ResourceManager.GetString("Volunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VolunteerEmailInput.
        /// </summary>
        public static string VolunteerEmailInput {
            get {
                return ResourceManager.GetString("VolunteerEmailInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volunteerformhead.
        /// </summary>
        public static string volunteerformhead {
            get {
                return ResourceManager.GetString("volunteerformhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VolunteerLabel1.
        /// </summary>
        public static string VolunteerLabel1 {
            get {
                return ResourceManager.GetString("VolunteerLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteerlink.
        /// </summary>
        public static string Volunteerlink {
            get {
                return ResourceManager.GetString("Volunteerlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VolunteerName.
        /// </summary>
        public static string VolunteerName {
            get {
                return ResourceManager.GetString("VolunteerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VolunteerNameInput.
        /// </summary>
        public static string VolunteerNameInput {
            get {
                return ResourceManager.GetString("VolunteerNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VYes.
        /// </summary>
        public static string VYes {
            get {
                return ResourceManager.GetString("VYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlzhCare Hub A platform where there is a release of burden from Caregivers to their Old People for take care..
        /// </summary>
        public static string WebSiteFooterText {
            get {
                return ResourceManager.GetString("WebSiteFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works.
        /// </summary>
        public static string Works {
            get {
                return ResourceManager.GetString("Works", resourceCulture);
            }
        }
    }
}
